package ar.com.cipres.model;

import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;

// Generated 07-may-2015 12:44:03 by Hibernate Tools 3.4.0.CR1

/**
 * ArtDespaId generated by hbm2java
 */
public class ArtDespaId implements java.io.Serializable {

	private String artic;
	private Despachos despachos;

	public ArtDespaId() {
	}

	public ArtDespaId(String artic, Despachos despachos) {
		this.artic = artic;
		this.despachos = despachos;
	}

	public String getArtic() {
		return this.artic;
	}

	public void setArtic(String artic) {
		this.artic = artic;
	}
	
	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "despaNr")
	public Despachos getDespachos() {
		return despachos;
	}

	public void setDespachos(Despachos despachos) {
		this.despachos = despachos;
	}

	

}
