package ar.com.cipres.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * ArtMadre generated by hbm2java
 */
@Entity
@Table(name = "artmadre", schema = "ComunDistri.dbo")
public class ArticuloMadre implements java.io.Serializable {

	private String codArtMad;
	private String descArtMad;
	private String obser;
	

	public ArticuloMadre() {
	}

	public ArticuloMadre(String codArtMad) {
		this.codArtMad = codArtMad;
	}

	public ArticuloMadre(String codArtMad, String descArtMad, String obser) {
		this.codArtMad = codArtMad;
		this.descArtMad = descArtMad;
		this.obser = obser;
	}

	@Id
	@Column(name = "CodArtMad", unique = true, nullable = false, length = 13)
	public String getCodArtMad() {
		return this.codArtMad;
	}

	public void setCodArtMad(String codArtMad) {
		this.codArtMad = codArtMad;
	}

	@Column(name = "DescArtMad", length = 50)
	public String getDescArtMad() {
		return this.descArtMad;
	}

	public void setDescArtMad(String descArtMad) {
		this.descArtMad = descArtMad;
	}
	
	@Transient
	@Column(name = "Obser", length = 200)
	public String getObser() {
		return this.obser;
	}

	public void setObser(String obser) {
		this.obser = obser;
	}
	

	
}
