package ar.com.cipres.model;



// Generated 23/09/2011 12:11:03 by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ClieArticPrecio generated by hbm2java
 */
@Entity
@Table(name = "cliearticprecio", schema = " ComunNewDistri.dbo")
public class ClieArticPrecio implements java.io.Serializable {

	private ClieArticPrecioId id;
	private BigDecimal p1;
	private BigDecimal p2;
	private BigDecimal p3;
	private BigDecimal p4;
	private BigDecimal p5;
	private BigDecimal p6;

	public ClieArticPrecio() {
	}

	public ClieArticPrecio(ClieArticPrecioId id, BigDecimal p1, BigDecimal p2,
			BigDecimal p3, BigDecimal p4, BigDecimal p5, BigDecimal p6) {
		this.id = id;
		this.p1 = p1;
		this.p2 = p2;
		this.p3 = p3;
		this.p4 = p4;
		this.p5 = p5;
		this.p6 = p6;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "genteNr", column = @Column(name = "GenteNr", nullable = false)),
			@AttributeOverride(name = "articulo", column = @Column(name = "Articulo", nullable = false, length = 13)) })
	public ClieArticPrecioId getId() {
		return this.id;
	}

	public void setId(ClieArticPrecioId id) {
		this.id = id;
	}

	@Column(name = "p1", nullable = false, scale = 4)
	public BigDecimal getP1() {
		return this.p1;
	}

	public void setP1(BigDecimal p1) {
		this.p1 = p1;
	}

	@Column(name = "p2", nullable = false, scale = 4)
	public BigDecimal getP2() {
		return this.p2;
	}

	public void setP2(BigDecimal p2) {
		this.p2 = p2;
	}

	@Column(name = "p3", nullable = false, scale = 4)
	public BigDecimal getP3() {
		return this.p3;
	}

	public void setP3(BigDecimal p3) {
		this.p3 = p3;
	}

	@Column(name = "p4", nullable = false, scale = 4)
	public BigDecimal getP4() {
		return this.p4;
	}

	public void setP4(BigDecimal p4) {
		this.p4 = p4;
	}

	@Column(name = "p5", nullable = false, scale = 4)
	public BigDecimal getP5() {
		return this.p5;
	}

	public void setP5(BigDecimal p5) {
		this.p5 = p5;
	}

	@Column(name = "p6", nullable = false, scale = 4)
	public BigDecimal getP6() {
		return this.p6;
	}

	public void setP6(BigDecimal p6) {
		this.p6 = p6;
	}

}
