package ar.com.cipres.model;




// Generated 23/09/2011 12:11:03 by Hibernate Tools 3.2.0.b9

import javax.persistence.Embeddable;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;

/**
 * ClieArticPrecioId generated by hbm2java
 */
@Embeddable
public class ClieArticPrecioId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Gente gente;
	private Stock stock;

	public ClieArticPrecioId() {
	}

	public ClieArticPrecioId(Gente gente, Stock stock) {
		this.gente = gente;
		this.stock = stock;
	}
	
	@OneToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="genteNr")
	public Gente getGente() {
		return gente;
	}

	public void setGente(Gente gente) {
		this.gente = gente;
	}


	@OneToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="articulo")
	public Stock getStock() {
		return stock;
	}

	public void setStock(Stock stock) {
		this.stock = stock;
	}

}
