package ar.com.cipres.model;

// Generated 14-abr-2015 22:56:54 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Despachos generated by hbm2java
 */
@Entity
@Table(name = "despachos", schema = "ComunSql.dbo")
public class Despachos implements java.io.Serializable {

	private int despaNr;
	private String descrip;
	private Date fechaIng;
	private String obser;
	private String soloLote;
	private Integer exinr;
	private Integer trazable;

	public Despachos() {
	}

	public Despachos(int despaNr) {
		this.despaNr = despaNr;
	}

	public Despachos(int despaNr, String descrip, Date fechaIng, String obser,
			String soloLote, Integer exinr) {
		this.despaNr = despaNr;
		this.descrip = descrip;
		this.fechaIng = fechaIng;
		this.obser = obser;
		this.soloLote = soloLote;
		this.exinr = exinr;
	}
	
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	public int getDespaNr() {
		return this.despaNr;
	}

	public void setDespaNr(int despaNr) {
		this.despaNr = despaNr;
	}

	public String getDescrip() {
		return this.descrip;
	}

	public void setDescrip(String descrip) {
		this.descrip = descrip;
	}

	public Date getFechaIng() {
		return this.fechaIng;
	}

	public void setFechaIng(Date fechaIng) {
		this.fechaIng = fechaIng;
	}

	public String getObser() {
		return this.obser;
	}

	public void setObser(String obser) {
		this.obser = obser;
	}

	public String getSoloLote() {
		return this.soloLote;
	}

	public void setSoloLote(String soloLote) {
		this.soloLote = soloLote;
	}

	public Integer getExinr() {
		return this.exinr;
	}

	public void setExinr(Integer exinr) {
		this.exinr = exinr;
	}

	public Integer getTrazable() {
		return trazable;
	}

	public void setTrazable(Integer trazable) {
		this.trazable = trazable;
	}
	
	

}
