package ar.com.cipres.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Domicilios generated by hbm2java
 */
@Entity
@Table(name = "domiciliosanexo", schema = " trazaweb.dbo")
public class DomiciliosAnexo implements java.io.Serializable {
	
	private Integer genteId;
	private Integer id;
	private Double latitud;
	private Double longitud;
	private String strProvincia;
	

	public DomiciliosAnexo() {
	}

	@Id	
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "GenteNr")
	public Integer getGenteId() {
		return this.genteId;
	}

	public void setGenteId(Integer genteId) {
		this.genteId = genteId;
	}

	
	@Column(name = "provincia")
	public String getStrProvincia() {
		return strProvincia;
	}

	public void setStrProvincia(String strProvincia) {
		this.strProvincia = strProvincia;
	}

	public Double getLatitud() {
		return latitud;
	}

	public void setLatitud(Double latitud) {
		this.latitud = latitud;
	}

	public Double getLongitud() {
		return longitud;
	}

	public void setLongitud(Double longitud) {
		this.longitud = longitud;
	}

	

}

