package ar.com.cipres.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

/**
 * Domicilios generated by hbm2java
 */
@Entity
@Table(name = "domicilios", schema = "ComunDistri.dbo")
public class Domicilios implements java.io.Serializable {
	
	private Integer genteId;
	private Integer id;
	private String razonSocial;
	private String descripcion;
	private String domicilio;
	private String localidad;
	private String provincia;
	private String pais;
	private String codigoPostal;
	private String contacto;
	private String telefonoVoz;
	private String email;
	private String telefonoMovil;
	private String telefonoEmergencias;
	private String telefonoFax;
	private String web;
	private Short domicilioPrincipal;
	private Integer transporte;
	private Short domicilioEntrega;
	private Short domicilioCobranza;
	private Short domicilioMailing;
	private Integer provinciaId;
	private String gln;
	private String nrAfiliado;
	private String nombreAfiliado;
	private String apellidoAfiliado;
	private String calleAfiliado;
	private String calleAltura;
	private String departamento;
	private String piso;
	private String tipoDoc;
	private String nrDocumento;
	private String descripC;
	private Integer otroLugar;
	private Boolean borrarDomicilio;		
	private DomiciliosAnexo domiciliosAnexo;

	public Domicilios() {
	}

	public Domicilios(Integer id, Integer genteId, String razonSocial, String descripcion, String domicilio, String localidad,
			String provincia, String pais, String codigoPostal, String contacto, String telefonoVoz, String email, String telefonoMovil, 
			String telefonoEmergencias, String telefonoFax, String web, Short domicilioPrincipal, Integer transporte,
			Short domicilioEntrega, Short domicilioCobranza, Short domicilioMailing, Integer provinciaId) {
		this.id = id;
		this.genteId = genteId;		
		this.razonSocial = razonSocial;
		this.descripcion = descripcion;
		this.domicilio = domicilio;
		this.localidad = localidad;
		this.provincia = provincia;
		this.pais = pais;
		this.codigoPostal = codigoPostal;
		this.contacto = contacto;
		this.telefonoVoz = telefonoVoz;
		this.email = email;
		this.telefonoMovil = telefonoMovil;
		this.telefonoEmergencias = telefonoEmergencias;
		this.telefonoFax = telefonoFax;
		this.web = web;
		this.domicilioPrincipal = domicilioPrincipal;
		this.transporte = transporte;
		this.domicilioEntrega = domicilioEntrega;
		this.domicilioCobranza = domicilioCobranza;
		this.domicilioMailing = domicilioMailing;
		this.provinciaId = provinciaId;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "DomiNr")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "GenteNr")
	public Integer getGenteId() {
		return this.genteId;
	}

	public void setGenteId(Integer genteId) {
		this.genteId = genteId;
	}
	
	@Column(name = "RazonSocial", length = 50)
	public String getRazonSocial() {
		return this.razonSocial;
	}

	public void setRazonSocial(String razonSocial) {
		this.razonSocial = razonSocial;
	}

	@Column(name = "Descripcion", length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "Domicilio", length = 50)
	public String getDomicilio() {
		return this.domicilio;
	}

	public void setDomicilio(String domicilio) {
		this.domicilio = domicilio;
	}

	@Column(name = "Localidad", length = 50)
	public String getLocalidad() {
		return this.localidad;
	}

	public void setLocalidad(String localidad) {
		this.localidad = localidad;
	}

	@Column(name = "Provincia", length = 50)
	public String getProvincia() {
		return this.provincia;
	}

	public void setProvincia(String provincia) {
		this.provincia = provincia;
	}

	@Column(name = "Pais", length = 50)
	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	@Column(name = "CP", length = 15)
	public String getCodigoPostal() {
		return this.codigoPostal;
	}

	public void setCodigoPostal(String codigoPostal) {
		this.codigoPostal = codigoPostal;
	}

	@Column(name = "Contacto", length = 50)
	public String getContacto() {
		return this.contacto;
	}

	public void setContacto(String contacto) {
		this.contacto = contacto;
	}

	@Column(name = "TeVoz", length = 50)
	public String getTelefonoVoz() {
		return this.telefonoVoz;
	}

	public void setTelefonoVoz(String telefonoVoz) {
		this.telefonoVoz = telefonoVoz;
	}

	@Column(name = "Internet", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "TeMovil", length = 50)
	public String getTelefonoMovil() {
		return this.telefonoMovil;
	}

	public void setTelefonoMovil(String telefonoMovil) {
		this.telefonoMovil = telefonoMovil;
	}

	@Column(name = "TeEmerg", length = 50)
	public String getTelefonoEmergencias() {
		return this.telefonoEmergencias;
	}

	public void setTelefonoEmergencias(String telefonoEmergencias) {
		this.telefonoEmergencias = telefonoEmergencias;
	}

	@Column(name = "TeFax", length = 50)
	public String getTelefonoFax() {
		return this.telefonoFax;
	}

	public void setTelefonoFax(String telefonoFax) {
		this.telefonoFax = telefonoFax;
	}

	@Column(name = "TeComp", length = 50)
	public String getWeb() {
		return this.web;
	}

	public void setWeb(String web) {
		this.web = web;
	}

	@Column(name = "DomiPrincipal")
	public Short getDomicilioPrincipal() {
		return this.domicilioPrincipal;
	}

	public void setDomicilioPrincipal(Short domicilioPrincipal) {
		this.domicilioPrincipal = domicilioPrincipal;
	}

	@Column(name = "Transporte")
	public Integer getTransporte() {
		return this.transporte;
	}

	public void setTransporte(Integer transporte) {
		this.transporte = transporte;
	}

	@Column(name = "DomiEntrega")
	public Short getDomicilioEntrega() {
		return this.domicilioEntrega;
	}

	public void setDomicilioEntrega(Short domicilioEntrega) {
		this.domicilioEntrega = domicilioEntrega;
	}

	@Column(name = "DomiCobranza")
	public Short getDomicilioCobranza() {
		return this.domicilioCobranza;
	}

	public void setDomicilioCobranza(Short domicilioCobranza) {
		this.domicilioCobranza = domicilioCobranza;
	}

	@Column(name = "DomiMailing")
	public Short getDomicilioMailing() {
		return this.domicilioMailing;
	}

	public void setDomicilioMailing(Short domicilioMailing) {
		this.domicilioMailing = domicilioMailing;
	}

	@Column(name = "CodProv", nullable = false)
	public Integer getProvinciaId() {
		return this.provinciaId;
	}

	public void setProvinciaId(Integer provinciaId) {
		this.provinciaId = provinciaId;
	}

	@Column(name = "GLN", nullable = false)
	public String getGln() {
		return this.gln;
	}

	public void setGln(String gln) {
		this.gln = gln;
	}

	@Transient
	public String getDescripC() {
		this.descripC = "[" + id + "] " + domicilio + " | " + descripcion ;
		return "[" + id + "] " + domicilio + " | " + descripcion;
	}
	
	@Transient
	public Boolean getBorrarDomicilio() {
		return borrarDomicilio != null ? borrarDomicilio : false;
	}

	public void setBorrarDomicilio(Boolean borrarDomicilio) {
		this.borrarDomicilio = borrarDomicilio;
	}

	public String getNrAfiliado() {
		return nrAfiliado;
	}

	public void setNrAfiliado(String nrAfiliado) {
		this.nrAfiliado = nrAfiliado;
	}

	

	public String getNombreAfiliado() {
		return nombreAfiliado;
	}

	public void setNombreAfiliado(String nombreAfiliado) {
		this.nombreAfiliado = nombreAfiliado;
	}

	public String getApellidoAfiliado() {
		return apellidoAfiliado;
	}

	public void setApellidoAfiliado(String apellidoAfiliado) {
		this.apellidoAfiliado = apellidoAfiliado;
	}

	public String getCalleAfiliado() {
		return calleAfiliado;
	}

	public void setCalleAfiliado(String calleAfiliado) {
		this.calleAfiliado = calleAfiliado;
	}

	public String getCalleAltura() {
		return calleAltura;
	}

	public void setCalleAltura(String calleAltura) {
		this.calleAltura = calleAltura;
	}

	public String getDepartamento() {
		return departamento;
	}

	public void setDepartamento(String departamento) {
		this.departamento = departamento;
	}

	public String getPiso() {
		return piso;
	}

	public void setPiso(String piso) {
		this.piso = piso;
	}

	public String getTipoDoc() {
		return tipoDoc;
	}

	public void setTipoDoc(String tipoDoc) {
		this.tipoDoc = tipoDoc;
	}

	public String getNrDocumento() {
		return nrDocumento;
	}

	public void setNrDocumento(String nrDocumento) {
		this.nrDocumento = nrDocumento;
	}

	public void setDescripC(String descripC) {
		this.descripC = descripC;
	}

	public Integer getOtroLugar() {
		return otroLugar;
	}

	public void setOtroLugar(Integer otroLugar) {
		this.otroLugar = otroLugar;
	}

	@OneToOne(fetch = FetchType.EAGER)
	@NotFound(action = NotFoundAction.IGNORE)
	@JoinColumn(name = "domiNr", insertable =  false, updatable = false)
	public DomiciliosAnexo getDomiciliosAnexo() {
		return domiciliosAnexo;
	}

	public void setDomiciliosAnexo(DomiciliosAnexo domiciliosAnexo) {
		this.domiciliosAnexo = domiciliosAnexo;
	}
	
}

