package ar.com.cipres.model;

// Generated 23/09/2011 12:11:03 by Hibernate Tools 3.2.0.b9

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;

/**
 * DomiciliosId generated by hbm2java
 */
@Embeddable
public class DomiciliosId implements java.io.Serializable {

	private Gente gente;
	private Integer domiNr;

	public DomiciliosId() {
	}

	public DomiciliosId(Gente gente, Integer domiNr) {
		this.gente = gente;
		this.domiNr = domiNr;
	}

	
	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "genteNr")
	public Gente getGente() {
		return gente;
	}

	public void setGente(Gente gente) {
		this.gente = gente;
	}

	@GeneratedValue(strategy = javax.persistence.GenerationType.IDENTITY)
	@Column(name = "DomiNr", nullable = false)
	public Integer getDomiNr() {
		return this.domiNr;
	}

	public void setDomiNr(Integer domiNr) {
		this.domiNr = domiNr;
	}


}
