package ar.com.cipres.model;

// Generated 23/09/2011 12:11:03 by Hibernate Tools 3.2.0.b9

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Existencias generated by hbm2java
 */
@Entity
@Table(name = "existenciasindicadores", schema = "trazaweb.dbo")
public class ExistenciasIndicadores implements java.io.Serializable {

	private Integer id;
	private Integer nrExistencia;
	private Integer nrIndicador;

	public ExistenciasIndicadores() {
		
		
	}

	@Id
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getNrExistencia() {
		return nrExistencia;
	}

	public void setNrExistencia(Integer nrExistencia) {
		this.nrExistencia = nrExistencia;
	}

	public Integer getNrIndicador() {
		return nrIndicador;
	}

	public void setNrIndicador(Integer nrIndicador) {
		this.nrIndicador = nrIndicador;
	}


}
