package ar.com.cipres.model;



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Gente generated by hbm2java
 */
@Entity
@Table(name = "gente", schema = "ComunNewDistri.dbo")
public class GenteShort implements java.io.Serializable {

	
	private Integer genteNr;	
	private String razonSocial;
	private String cuit;
	private Short proveedor;
	private Integer nrObraSocial;
	
	@Id
	public Integer getGenteNr() {
		return genteNr;
	}
	public void setGenteNr(Integer genteNr) {
		this.genteNr = genteNr;
	}
	
	@Column(name = "\"Razon Social\"", length = 50, nullable = true)
	public String getRazonSocial() {
		return razonSocial;
	}
	public void setRazonSocial(String razonSocial) {
		this.razonSocial = razonSocial;
	}
	public String getCuit() {
		return cuit;
	}
	public void setCuit(String cuit) {
		this.cuit = cuit;
	}
	
	@Column(name = "Proveed", nullable = true)
	public Short getProveedor() {
		return this.proveedor;
	}

	public void setProveedor(Short proveedor) {
		this.proveedor = proveedor;
	}
	public Integer getNrObraSocial() {
		return nrObraSocial;
	}
	public void setNrObraSocial(Integer nrObraSocial) {
		this.nrObraSocial = nrObraSocial;
	}
	
	
	
	
	
}

