package ar.com.cipres.model;

// Generated 23/09/2011 12:11:03 by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.DynamicInsert;

import com.google.gson.annotations.Expose;

/**
 * Gente generated by hbm2java
 */
@Entity
@DynamicInsert
@Table(name = "gente", schema = "ComunSql.dbo")
public class Gente implements java.io.Serializable {
	@Expose
	private Integer id;
	@Expose
	private String razonSocial;
	private Date fechaIngreso;
	private Integer relacionId;
	private Short cliente;
	private Short proveedor;
	private String observaciones;
	@Expose
	private String cuit;
	private Integer provinciaId;
	private Integer zonaId;
	private Integer vendedorId;
	private Integer cobradorId;
	private Integer condicionVenta;
	private Float comisionVenta;
	private Float comisionCobrador;
	private Integer tipoIvaId;
	private BigDecimal creditoCuenta;
	private BigDecimal creditoCheques;
	private Short noFactura;	// Todo: Ver para que es
	private Short marcado1;		// Todo: Ver para que es
	private Short marcado2;		// Todo: Ver para que es
	private Short marcado3;		// Todo: Ver para que es
	private Short activGrav;
	private Integer vencimientoDias;
	private String proveedorNr;
	private Integer codImputacionContableId;
	private Short percibeIb;
	private Short percibeIva;
	private Float bonifStd;
	private String numeroIb;
	private Integer listaPrecio;
	private Integer nrObraSocial;
	private Double saldo;
	
	private Domicilios domicilioPricipal;
	private String descripC;
	private Integer idRol;
	List<Domicilios> domicilioList = new ArrayList<Domicilios>();
 
	@Transient
	public String getDescripC() {
		this.descripC = "[" + id + "] " + razonSocial; 
		return descripC;
	}
	
	@Transient
	public List<Domicilios> getDomicilioList() {
		return domicilioList;
	}

	public void setDomicilioList(List<Domicilios> domicilioList) {
		this.domicilioList = domicilioList;
	}

	public void setDescripC(String descripC) {
		this.descripC = descripC;
	}

	public Gente() {
	}

	public Gente(Integer id, Integer relacionId, Short cliente, Short proveedor,
			Integer provinciaId, Integer zonaId, Integer vendedorId, Integer cobradorId,
			Integer condicionVenta, Float comisionVenta, Float comisionCobrador, Integer tipoIvaId,
			BigDecimal creditoCuenta, BigDecimal creditoCheques, Short noFactura,
			Short marcado1, Short marcado2, Short marcado3, Short activGrav,
			Integer codImputacionContableId, Short percibeIb, Short percibeIva, Float bonifStd,
			Integer listaPrecio) {
		this.id = id;
		this.relacionId = relacionId;
		this.cliente = cliente;
		this.proveedor = proveedor;
		this.provinciaId = provinciaId;
		this.zonaId = zonaId;
		this.vendedorId = vendedorId;
		this.cobradorId = cobradorId;
		this.condicionVenta = condicionVenta;
		this.comisionVenta = comisionVenta;
		this.comisionCobrador = comisionCobrador;
		this.tipoIvaId = tipoIvaId;
		this.creditoCuenta = creditoCuenta;
		this.creditoCheques = creditoCheques;
		this.noFactura = noFactura;
		this.marcado1 = marcado1;
		this.marcado2 = marcado2;
		this.marcado3 = marcado3;
		this.activGrav = activGrav;
		this.codImputacionContableId = codImputacionContableId;
		this.percibeIb = percibeIb;
		this.percibeIva = percibeIva;
		this.bonifStd = bonifStd;
		this.listaPrecio = listaPrecio;
	}

	public Gente(Integer id, String razonSocial, Date fechaIngreso,
			Integer relacionId, Short cliente, Short proveedor, String observaciones,
			String cuit, Integer provinciaId, Integer zonaId, Integer vendedorId,
			Integer cobradorId, Integer condicionVenta, Float comisionVenta, Float comisionCobrador,
			Integer tipoIvaId, BigDecimal creditoCuenta, BigDecimal creditoCheques,
			Short noFactura, Short marcado1, Short marcado2, Short marcado3,
			Short activGrav, Integer vencimientoDias, String proveedorNr,
			Integer codImputacionContableId, Short percibeIb, Short percibeIva, Float bonifStd,
			String numeroIb, Integer listaPrecio, Set domicilioses) {
		this.id = id;
		this.razonSocial = razonSocial;
		this.fechaIngreso = fechaIngreso;
		this.relacionId = relacionId;
		this.cliente = cliente;
		this.proveedor = proveedor;
		this.observaciones = observaciones;
		this.cuit = cuit;
		this.provinciaId = provinciaId;
		this.zonaId = zonaId;
		this.vendedorId = vendedorId;
		this.cobradorId = cobradorId;
		this.condicionVenta = condicionVenta;
		this.comisionVenta = comisionVenta;
		this.comisionCobrador = comisionCobrador;
		this.tipoIvaId = tipoIvaId;
		this.creditoCuenta = creditoCuenta;
		this.creditoCheques = creditoCheques;
		this.noFactura = noFactura;
		this.marcado1 = marcado1;
		this.marcado2 = marcado2;
		this.marcado3 = marcado3;
		this.activGrav = activGrav;
		this.vencimientoDias = vencimientoDias;
		this.proveedorNr = proveedorNr;
		this.codImputacionContableId = codImputacionContableId;
		this.percibeIb = percibeIb;
		this.percibeIva = percibeIva;
		this.bonifStd = bonifStd;
		this.numeroIb = numeroIb;
		this.listaPrecio = listaPrecio;
	}

	@Id
	@Column(name = "GenteNr", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer genteNr) {
		this.id = genteNr;
	}

	@Column(name = "\"Razon Social\"", length = 50, nullable = true)
	public String getRazonSocial() {
		return this.razonSocial;
	}

	public void setRazonSocial(String razonSocial) {
		this.razonSocial = razonSocial;
	}

	@Column(name = "\"Fecha Ingreso\"", length = 16, nullable = true)
	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	@Column(name = "Relacion", nullable = true)
	public Integer getRelacionId() {
		return this.relacionId;
	}

	public void setRelacionId(Integer relacionId) {
		this.relacionId = relacionId;
	}

	@Column(name = "Cliente", nullable = true)
	public Short getCliente() {
		return this.cliente;
	}

	public void setCliente(Short cliente) {
		this.cliente = cliente;
	}

	@Column(name = "Proveed", nullable = true)
	public Short getProveedor() {
		return this.proveedor;
	}

	public void setProveedor(Short proveedor) {
		this.proveedor = proveedor;
	}

	@Column(name = "Observacion", nullable = true)
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	@Column(name = "Cuit", length = 15, nullable = true)
	public String getCuit() {
		return this.cuit;
	}

	public void setCuit(String cuit) {
		this.cuit = cuit;
	}

	@Column(name = "ProvNr", nullable = true)
	public Integer getProvinciaId() {
		return this.provinciaId;
	}

	public void setProvinciaId(Integer provinciaId) {
		this.provinciaId = provinciaId;
	}

	@Column(name = "ZonaNr", nullable = true)
	public Integer getZonaId() {
		return this.zonaId;
	}

	public void setZonaId(Integer zonaId) {
		this.zonaId = zonaId;
	}

	@Column(name = "VendedorNr", nullable = true)
	public Integer getVendedorId() {
		return this.vendedorId;
	}

	public void setVendedorId(Integer vendedorId) {
		this.vendedorId = vendedorId;
	}

	@Column(name = "CobradorNr", nullable = true)
	public Integer getCobradorId() {
		return this.cobradorId;
	}

	public void setCobradorId(Integer cobradorId) {
		this.cobradorId = cobradorId;
	}

	@Column(name = "CondVta", nullable = true)
	public Integer getCondicionVenta() {
		return this.condicionVenta;
	}

	public void setCondicionVenta(Integer condicionVenta) {
		this.condicionVenta = condicionVenta;
	}

	@Column(name = "ComisVta", nullable = true, precision = 24, scale = 0)
	public Float getComisionVenta() {
		return this.comisionVenta;
	}

	public void setComisionVenta(Float comisionVenta) {
		this.comisionVenta = comisionVenta;
	}

	@Column(name = "ComisCob", nullable = true, precision = 24, scale = 0)
	public Float getComisionCobrador() {
		return this.comisionCobrador;
	}

	public void setComisionCobrador(Float comisionCobrador) {
		this.comisionCobrador = comisionCobrador;
	}
	
	@Column(name = "TipoIva")
	public Integer getTipoIvaId() {
		return tipoIvaId;
	}

	public void setTipoIvaId(Integer tipoIvaId) {
		this.tipoIvaId = tipoIvaId;
	}

	
	@Column(name = "CredCta", nullable = true, scale = 4)
	public BigDecimal getCreditoCuenta() {
		return this.creditoCuenta;
	}

	public void setCreditoCuenta(BigDecimal creditoCuenta) {
		this.creditoCuenta = creditoCuenta;
	}

	@Column(name = "CredCheques", nullable = true, scale = 4)
	public BigDecimal getCreditoCheques() {
		return this.creditoCheques;
	}

	public void setCreditoCheques(BigDecimal credCheques) {
		this.creditoCheques= credCheques;
	}

	@Column(name = "NoFactura", nullable = true)
	public Short getNoFactura() {
		return this.noFactura;
	}

	public void setNoFactura(Short noFactura) {
		this.noFactura = noFactura;
	}

	@Column(name = "Marcado1", nullable = true)
	public Short getMarcado1() {
		return this.marcado1;
	}

	public void setMarcado1(Short marcado1) {
		this.marcado1 = marcado1;
	}

	@Column(name = "Marcado2", nullable = true)
	public Short getMarcado2() {
		return this.marcado2;
	}

	public void setMarcado2(Short marcado2) {
		this.marcado2 = marcado2;
	}

	@Column(name = "Marcado3", nullable = true)
	public Short getMarcado3() {
		return this.marcado3;
	}

	public void setMarcado3(Short marcado3) {
		this.marcado3 = marcado3;
	}
	
	
	@Column(name = "ActivGrav")
	public Short getActivGrav() {
		return this.activGrav;
	}

	public void setActivGrav(Short activGrav) {
		this.activGrav = activGrav;
	}

	@Column(name = "NrAnterior")
	public Integer getVencimientoDias() {
		return this.vencimientoDias;
	}

	public void setVencimientoDias(Integer vencimientoDias) {
		this.vencimientoDias = vencimientoDias;
	}

	@Column(name = "ProveedorNr", length = 15)
	public String getProveedorNr() {
		return this.proveedorNr;
	}

	public void setProveedorNr(String proveedorNr) {
		this.proveedorNr = proveedorNr;
	}

	@Column(name = "CodImpuCont", nullable = true)
	public Integer getCodImputacionContableId() {
		return this.codImputacionContableId;
	}

	public void setCodImputacionContableId(Integer codImputacionContableId) {
		this.codImputacionContableId = codImputacionContableId;
	}

	@Column(name = "PercibeIb", nullable = true)
	public Short getPercibeIb() {
		return this.percibeIb;
	}

	public void setPercibeIb(Short percibeIb) {
		this.percibeIb = percibeIb;
	}

	@Column(name = "PercibeIva", nullable = true)
	public Short getPercibeIva() {
		return this.percibeIva;
	}

	public void setPercibeIva(Short percibeIva) {
		this.percibeIva = percibeIva;
	}

	@Column(name = "BonifStd", nullable = true, precision = 24, scale = 0)
	public Float getBonifStd() {
		return this.bonifStd;
	}

	public void setBonifStd(Float bonifStd) {
		this.bonifStd = bonifStd;
	}

	@Column(name = "NrIngBru", length = 13)
	public String getNumeroIb() {
		return this.numeroIb;
	}

	public void setNumeroIb(String numeroIb) {
		this.numeroIb = numeroIb;
	}

	@Column(name = "ListaPrecio", nullable = true)
	public Integer getListaPrecio() {
		return this.listaPrecio;
	}

	public void setListaPrecio(Integer listaPrecio) {
		this.listaPrecio = listaPrecio;
	}

	@Transient
	public Domicilios getDomicilioPricipal() {
		return domicilioPricipal;
	}

	public void setDomicilioPricipal(Domicilios domicilioPricipal) {
		this.domicilioPricipal = domicilioPricipal;
	}

	@Transient
	public Integer getIdRol() {
		return idRol;
	}

	public void setIdRol(Integer idRol) {
		this.idRol = idRol;
	}

	public Integer getNrObraSocial() {
		return nrObraSocial;
	}

	public void setNrObraSocial(Integer nrObraSocial) {
		this.nrObraSocial = nrObraSocial;
	}
	
	@Transient
	public Double getSaldo() {
		return saldo;
	}

	public void setSaldo(Double saldo) {
		this.saldo = saldo;
	}
	
	

}

