package ar.com.cipres.model;

// Generated 02-may-2015 19:07:55 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Kardex generated by hbm2java
 */
@Entity
@Table(name = "kardexshort", schema = "")
public class KardexShort implements java.io.Serializable {

	private KardexId id;
	private int existenciaNr;
	private Date fechaComprob;
	private int tipoComprobante;
	private int transacOrigen;
	private Float cantidad1;
	private Double preFob;
	private Integer operadorNr;
	private Date fechaTransac;
	private Integer agendadoNr;
	private String obser;
	public KardexShort() {
	}

	

	
	@EmbeddedId
	@AttributeOverrides({
		@AttributeOverride(name = "transacNr", column = @Column(name = "transacNr", nullable = false)),
		@AttributeOverride(name = "clave", column = @Column(name = "clave", nullable = false)) })
	public KardexId getId() {
		return this.id;
	}

	public void setId(KardexId id) {
		this.id = id;
	}

	public int getExistenciaNr() {
		return this.existenciaNr;
	}

	public void setExistenciaNr(int existenciaNr) {
		this.existenciaNr = existenciaNr;
	}


	public Date getFechaComprob() {
		return this.fechaComprob;
	}

	public void setFechaComprob(Date fechaComprob) {
		this.fechaComprob = fechaComprob;
	}

	public int getTipoComprobante() {
		return this.tipoComprobante;
	}

	public void setTipoComprobante(int tipoComprobante) {
		this.tipoComprobante = tipoComprobante;
	}

	public int getTransacOrigen() {
		return this.transacOrigen;
	}

	public void setTransacOrigen(int transacOrigen) {
		this.transacOrigen = transacOrigen;
	}

	public float getCantidad1() {
		return this.cantidad1;
	}

	public void setCantidad1(Float cantidad1) {
		this.cantidad1 = cantidad1;
	}


	

	public int getOperadorNr() {
		return this.operadorNr;
	}

	public void setOperadorNr(int operadorNr) {
		this.operadorNr = operadorNr;
	}


	public Date getFechaTransac() {
		return this.fechaTransac;
	}

	public void setFechaTransac(Date fechaTransac) {
		this.fechaTransac = fechaTransac;
	}

	public int getAgendadoNr() {
		return this.agendadoNr;
	}

	public void setAgendadoNr(int agendadoNr) {
		this.agendadoNr = agendadoNr;
	}

	public String getObser() {
		return this.obser;
	}

	public void setObser(String obser) {
		this.obser = obser;
	}
	
	public Double getPreFob() {
		return preFob;
	}

	public void setPreFob(Double preFob) {
		this.preFob = preFob;
	}
	
	

}
