package ar.com.cipres.model;

// Generated 02-may-2015 19:07:55 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Kardex generated by hbm2java
 */
@Entity
@Table(name = "kardex", schema = "NewDistri.dbo")
public class Kardex implements java.io.Serializable {

	private KardexId id;
	private int existenciaNr;
	private Integer articNr;
	private Date fechaComprob;
	private int tipoComprobante;
	private int transacOrigen;
	private Float cantidad1;
	private Float cantidad2;
	private Double subtotal;
	private BigDecimal preVta;
	private BigDecimal preCosto;
	private Double preFob;
	private Integer operadorNr;
	private Integer sucursalNr;
	private Integer vendedorNr;
	private Date fechaTransac;
	private Integer agendadoNr;
	private String obser;
	private String talle;
	private Integer colo;
	private Despachos despachos;
	public Kardex() {
	}

	

	
	@EmbeddedId
	@AttributeOverrides({
		@AttributeOverride(name = "transacNr", column = @Column(name = "transacNr", nullable = false)),
		@AttributeOverride(name = "clave", column = @Column(name = "clave", nullable = false)) })
	public KardexId getId() {
		return this.id;
	}

	public void setId(KardexId id) {
		this.id = id;
	}

	public int getExistenciaNr() {
		return this.existenciaNr;
	}

	public void setExistenciaNr(int existenciaNr) {
		this.existenciaNr = existenciaNr;
	}

	public Integer getArticNr() {
		return this.articNr;
	}

	public void setArticNr(Integer articNr) {
		this.articNr = articNr;
	}

	public Date getFechaComprob() {
		return this.fechaComprob;
	}

	public void setFechaComprob(Date fechaComprob) {
		this.fechaComprob = fechaComprob;
	}

	public int getTipoComprobante() {
		return this.tipoComprobante;
	}

	public void setTipoComprobante(int tipoComprobante) {
		this.tipoComprobante = tipoComprobante;
	}

	public int getTransacOrigen() {
		return this.transacOrigen;
	}

	public void setTransacOrigen(int transacOrigen) {
		this.transacOrigen = transacOrigen;
	}

	public float getCantidad1() {
		return this.cantidad1;
	}

	public void setCantidad1(Float cantidad1) {
		this.cantidad1 = cantidad1;
	}

	public Float getCantidad2() {
		return this.cantidad2;
	}

	public void setCantidad2(Float cantidad2) {
		this.cantidad2 = cantidad2;
	}

	public Double getSubtotal() {
		return this.subtotal;
	}

	public void setSubtotal(Double subtotal) {
		this.subtotal = subtotal;
	}

	public BigDecimal getPreVta() {
		return this.preVta;
	}

	public void setPreVta(BigDecimal preVta) {
		this.preVta = preVta;
	}

	public BigDecimal getPreCosto() {
		return this.preCosto;
	}

	public void setPreCosto(BigDecimal preCosto) {
		this.preCosto = preCosto;
	}


	

	public int getOperadorNr() {
		return this.operadorNr;
	}

	public void setOperadorNr(int operadorNr) {
		this.operadorNr = operadorNr;
	}

	public int getSucursalNr() {
		return this.sucursalNr;
	}

	public void setSucursalNr(int sucursalNr) {
		this.sucursalNr = sucursalNr;
	}

	public int getVendedorNr() {
		return this.vendedorNr;
	}

	public void setVendedorNr(int vendedorNr) {
		this.vendedorNr = vendedorNr;
	}

	public Date getFechaTransac() {
		return this.fechaTransac;
	}

	public void setFechaTransac(Date fechaTransac) {
		this.fechaTransac = fechaTransac;
	}

	public int getAgendadoNr() {
		return this.agendadoNr;
	}

	public void setAgendadoNr(int agendadoNr) {
		this.agendadoNr = agendadoNr;
	}

	public String getObser() {
		return this.obser;
	}

	public void setObser(String obser) {
		this.obser = obser;
	}

	public String getTalle() {
		return this.talle;
	}

	public void setTalle(String talle) {
		this.talle = talle;
	}

	public Integer getColo() {
		return this.colo;
	}

	public void setColo(Integer colo) {
		this.colo = colo;
	}

	public Double getPreFob() {
		return preFob;
	}

	public void setPreFob(Double preFob) {
		this.preFob = preFob;
	}
	
	@Transient
	public Despachos getDespachos() {
		return despachos;
	}

	public void setDespachos(Despachos despachos) {
		this.despachos = despachos;
	}
	

}
