package ar.com.cipres.model;

import javax.persistence.Embeddable;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;


/**
 * KardexId generated by hbm2java
 */
@Embeddable
public class KardexId implements java.io.Serializable {

	private Integer transacNr;
	private Stock stock;

	public KardexId() {
	}

	public KardexId(Integer transacNr, Stock stock) {
		this.transacNr = transacNr;
		this.stock = stock;
	}

	
	public Integer getTransacNr() {
		return this.transacNr;
	}

	public void setTransacNr(Integer transacNr) {
		this.transacNr = transacNr;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "claveArticulo")	
	public Stock getStock() {
		return this.stock;
	}

	public void setStock(Stock stock) {
		this.stock = stock;
	}

	

	

}
