package ar.com.cipres.model;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

// Generated 04-may-2015 1:14:29 by Hibernate Tools 3.4.0.CR1

/**
 * NumerKar generated by hbm2java
 */
@Entity
@Table(name = "numerkar", schema = "NewDistri.dbo")
public class NumerKar implements java.io.Serializable {

	private Integer nr;
	private Integer letraA;

	public NumerKar() {
	}

	public NumerKar(Integer nr, Integer letraA) {
		this.nr = nr;
		this.letraA = letraA;
	}

	@Id
	public Integer getNr() {
		return this.nr;
	}

	public void setNr(Integer nr) {
		this.nr = nr;
	}

	public Integer getLetraA() {
		return this.letraA;
	}

	public void setLetraA(Integer letraA) {
		this.letraA = letraA;
	}

}
