package ar.com.cipres.model;

// Generated 23/09/2011 12:11:03 by Hibernate Tools 3.2.0.b9

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Operadores generated by hbm2java
 */
@Entity
@Table(name = "operadores", schema = "ComunDistri.dbo")
public class Operadores implements java.io.Serializable {

	private Integer operNr;
	private String operNombre;
	private String operObser;
	private String operClave;
	private String descripC;
	
	
	@Transient
	public String getDescripC() {
		this.descripC = "[" + operNr + "] " + operNombre; 
		return descripC;
	}

	public void setDescripC(String descripC) {
		this.descripC = descripC;
	}

	public Operadores() {
	}

	public Operadores(Integer operNr) {
		this.operNr = operNr;
	}

	public Operadores(Integer operNr, String operNombre, String operObser,
			String operClave) {
		this.operNr = operNr;
		this.operNombre = operNombre;
		this.operObser = operObser;
		this.operClave = operClave;
	}

	@Id
	@Column(name = "OperNr", unique = true, nullable = false)
	public Integer getOperNr() {
		return this.operNr;
	}

	public void setOperNr(Integer operNr) {
		this.operNr = operNr;
	}

	@Column(name = "OperNombre", length = 50)
	public String getOperNombre() {
		return this.operNombre;
	}

	public void setOperNombre(String operNombre) {
		this.operNombre = operNombre;
	}

	@Column(name = "OperObser", length = 16)
	public String getOperObser() {
		return this.operObser;
	}

	public void setOperObser(String operObser) {
		this.operObser = operObser;
	}

	@Column(name = "OperClave", length = 10)
	public String getOperClave() {
		return this.operClave;
	}

	public void setOperClave(String operClave) {
		this.operClave = operClave;
	}

}
