package ar.com.cipres.model;

// Generated 23/09/2011 12:11:03 by Hibernate Tools 3.2.0.b9

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Existencias generated by hbm2java
 */
@Entity
@Table(name = "prefijoexistencia", schema = "trazaweb.dbo")
public class PrefijoExistencia implements java.io.Serializable {

	private Integer id;
	private String nrprefijo;
	private Integer nrExistencia;

	@Id
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	

	public String getNrprefijo() {
		return nrprefijo;
	}

	public void setNrprefijo(String nrprefijo) {
		this.nrprefijo = nrprefijo;
	}

	public Integer getNrExistencia() {
		return nrExistencia;
	}

	public void setNrExistencia(Integer nrExistencia) {
		this.nrExistencia = nrExistencia;
	}

	


}
