package ar.com.cipres.model;

// Generated 30/11/2014 21:27:08 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * Rol generated by hbm2java
 */
@Entity
//@Table(name = "rol", catalog = "produsimpa", uniqueConstraints = @UniqueConstraint(columnNames = "nombre"))
@Table(name = "rol", schema = "trazawebNewDistri.dbo")
public class Rol implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private String abrev;
	private String descripcion;
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);

	public Rol() {
	}

	public Rol(String nombre) {
		this.nombre = nombre;
	}

	public Rol(String nombre, String abrev, String descripcion, Set<Usuario> usuarios) {
		this.nombre = nombre;
		this.abrev = abrev;
		this.descripcion = descripcion;
		this.usuarios = usuarios;
	}

	@Id
	@Column(name = "id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nombre", unique = true, nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
	
	@Column(name = "abrev", unique = true, nullable = false, length = 50)
	public String getAbrev() {
		return this.abrev;
	}

	public void setAbrev(String abrev) {
		this.abrev = abrev;
	}

	@Column(name = "descripcion", length = 7000)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rol")
	@JsonIgnore
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

}
