package ar.com.cipres.model;

// Generated 23/09/2011 12:11:03 by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;
import java.sql.Blob;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Stock generated by hbm2java
 */
@Entity
@Table(name = "stock", schema = "ComunSql.dbo")
public class StockBasic implements java.io.Serializable {

	private String id;
	private Integer nrArt;
	private String descripcion;
	private Long fam;
	private Long subFam;	
	private String codBarras;
	
	private String descripC;
	private String gtin;
	
	public StockBasic() {
	}

	

	@Id
	@Column(name = "Clave", unique = true, nullable = false, length = 13)
	public String getId() {
		return this.id.trim();
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "NrArt")
	public Integer getNrArt() {
		return this.nrArt;
	}

	public void setNrArt(Integer nrArt) {
		this.nrArt = nrArt;
	}

	@Column(name = "Descripcion", length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	
	@Column(name = "Fam")
	public Long getFam() {
		return this.fam;
	}

	public void setFam(Long fam) {
		this.fam = fam;
	}

	@Column(name = "SubFam", nullable = false)
	public Long getSubFam() {
		return this.subFam;
	}

	public void setSubFam(Long subFam) {
		this.subFam = subFam;
	}

	
	

	@Column(name = "CodBarras", length = 13)
	public String getCodBarras() {
		return this.codBarras;
	}

	public void setCodBarras(String codBarras) {
		this.codBarras = codBarras;
	}

	
	

	
	

	@Transient
	public String getDescripC() {
		this.descripC = "[" + id + "] " + descripcion;
		return descripC;
	}

	public void setDescripC(String descripC) {
		this.descripC = descripC;
	}

	public String getGtin() {
		return gtin;
	}

	public void setGtin(String gtin) {
		this.gtin = gtin;
	}
	
	

}
