package ar.com.cipres.model;

// Generated 22/09/2011 00:18:30 by Hibernate Tools 3.2.0.b9

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TipoComprob generated by hbm2java
 */
@Entity
@Table(name = "tipocomprob", schema = "NewDistri.dbo")
public class TipoComprob implements java.io.Serializable {

	private Integer nr;
	private String descripcion = "";
	private Short factorStock;
	private Short factorCtaCte;
	private Short usaItems;
	private Integer contraAsiento;
	private Integer factorSubdiarios;
	private Integer factorFactCred;

	public TipoComprob() {
	}

	public TipoComprob(int nr) {
		this.nr = nr;
	}

	public TipoComprob(int nr, String descripcion, Short factorStock,
			Short factorCtaCte, Short usaItems, Integer contraAsiento,
			Integer factorSubdiarios, Integer factorFactCred) {
		this.nr = nr;
		this.descripcion = descripcion;
		this.factorStock = factorStock;
		this.factorCtaCte = factorCtaCte;
		this.usaItems = usaItems;
		this.contraAsiento = contraAsiento;
		this.factorSubdiarios = factorSubdiarios;
		this.factorFactCred = factorFactCred;
	}

	@Id
	@Column(name = "Nr", unique = true, nullable = false)
	public Integer getNr() {
		return this.nr;
	}

	public void setNr(Integer nr) {
		this.nr = nr;
	}

	@Column(name = "Descripcion", length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "FactorStock")
	public Short getFactorStock() {
		return this.factorStock;
	}

	public void setFactorStock(Short factorStock) {
		this.factorStock = factorStock;
	}

	@Column(name = "FactorCtaCte")
	public Short getFactorCtaCte() {
		return this.factorCtaCte;
	}

	public void setFactorCtaCte(Short factorCtaCte) {
		this.factorCtaCte = factorCtaCte;
	}

	@Column(name = "UsaItems")
	public Short getUsaItems() {
		return this.usaItems;
	}

	public void setUsaItems(Short usaItems) {
		this.usaItems = usaItems;
	}

	@Column(name = "ContraAsiento")
	public Integer getContraAsiento() {
		return this.contraAsiento;
	}

	public void setContraAsiento(Integer contraAsiento) {
		this.contraAsiento = contraAsiento;
	}

	@Column(name = "FactorSubdiarios")
	public Integer getFactorSubdiarios() {
		return this.factorSubdiarios;
	}

	public void setFactorSubdiarios(Integer factorSubdiarios) {
		this.factorSubdiarios = factorSubdiarios;
	}

	@Column(name = "FactorFactCred")
	public Integer getFactorFactCred() {
		return this.factorFactCred;
	}

	public void setFactorFactCred(Integer factorFactCred) {
		this.factorFactCred = factorFactCred;
	}

}
