package ar.com.cipres.model;

// Generated 13-abr-2015 2:38:24 by Hibernate Tools 3.4.0.CR1




/**
 * Trazabi generated by hbm2java
 */

public class TrazabiShort implements java.io.Serializable {

	private int nr;
	private String nrlote;
	private String glndestinoIng;
	public TrazabiShort() {
	}

	public TrazabiShort(int nr) {
		this.nr = nr;
	}

	
	
	public int getNr() {
		return this.nr;
	}

	public void setNr(int nr) {
		this.nr = nr;
	}

	public String getNrlote() {
		return nrlote;
	}

	public void setNrlote(String nrlote) {
		this.nrlote = nrlote;
	}

	public String getGlndestinoIng() {
		return glndestinoIng;
	}

	public void setGlndestinoIng(String glndestinoIng) {
		this.glndestinoIng = glndestinoIng;
	}



}
