package jmc.trazaweb;

// Generated 07-may-2015 12:44:03 by Hibernate Tools 3.4.0.CR1

/**
 * ArtDespaId generated by hbm2java
 */
public class ArtDespaId implements java.io.Serializable {

	private String artic;
	private int despaNr;

	public ArtDespaId() {
	}

	public ArtDespaId(String artic, int despaNr) {
		this.artic = artic;
		this.despaNr = despaNr;
	}

	public String getArtic() {
		return this.artic;
	}

	public void setArtic(String artic) {
		this.artic = artic;
	}

	public int getDespaNr() {
		return this.despaNr;
	}

	public void setDespaNr(int despaNr) {
		this.despaNr = despaNr;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ArtDespaId))
			return false;
		ArtDespaId castOther = (ArtDespaId) other;

		return ((this.getArtic() == castOther.getArtic()) || (this.getArtic() != null
				&& castOther.getArtic() != null && this.getArtic().equals(
				castOther.getArtic())))
				&& (this.getDespaNr() == castOther.getDespaNr());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getArtic() == null ? 0 : this.getArtic().hashCode());
		result = 37 * result + this.getDespaNr();
		return result;
	}

}
