package jmc.trazaweb;

// Generated 04-may-2015 1:14:29 by Hibernate Tools 3.4.0.CR1

/**
 * Numeraciones generated by hbm2java
 */
public class Numeraciones implements java.io.Serializable {

	private short nr;
	private String descrip;
	private float letraA;
	private float letraB;
	private float letraC;
	private float letraE;

	public Numeraciones() {
	}

	public Numeraciones(short nr, String descrip, float letraA, float letraB,
			float letraC, float letraE) {
		this.nr = nr;
		this.descrip = descrip;
		this.letraA = letraA;
		this.letraB = letraB;
		this.letraC = letraC;
		this.letraE = letraE;
	}

	public short getNr() {
		return this.nr;
	}

	public void setNr(short nr) {
		this.nr = nr;
	}

	public String getDescrip() {
		return this.descrip;
	}

	public void setDescrip(String descrip) {
		this.descrip = descrip;
	}

	public float getLetraA() {
		return this.letraA;
	}

	public void setLetraA(float letraA) {
		this.letraA = letraA;
	}

	public float getLetraB() {
		return this.letraB;
	}

	public void setLetraB(float letraB) {
		this.letraB = letraB;
	}

	public float getLetraC() {
		return this.letraC;
	}

	public void setLetraC(float letraC) {
		this.letraC = letraC;
	}

	public float getLetraE() {
		return this.letraE;
	}

	public void setLetraE(float letraE) {
		this.letraE = letraE;
	}

}
