package jmc.trazaweb;

// Generated 04-may-2015 1:14:29 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.sql.Blob;
import java.util.Date;

/**
 * Transac generated by hbm2java
 */
public class Transac implements java.io.Serializable {

	private int transacNr;
	private int genteNr;
	private Date fecha;
	private int tipoComprob;
	private String nrComprob;
	private String letra;
	private String prefijo;
	private int vendedor;
	private int cobrador;
	private int condiciones;
	private int tipoIva;
	private float alicuotaIva;
	private float sobreAlicIva;
	private float alicuotaInternos;
	private float valorMonExt;
	private Date fechaTransac;
	private short vencim1;
	private short vencim2;
	private short vencim3;
	private short vencim4;
	private int nrSucursal;
	private int nrOperador;
	private String observaciones;
	private BigDecimal netoGrav;
	private BigDecimal netoNoGrav;
	private BigDecimal iva;
	private BigDecimal ivaRni;
	private BigDecimal ivaPercep;
	private BigDecimal internos;
	private BigDecimal retIb;
	private BigDecimal retIva;
	private BigDecimal retGan;
	private BigDecimal retCargasSoc;
	private BigDecimal descuentos;
	private BigDecimal otrosImp1;
	private BigDecimal otrosImp2;
	private BigDecimal otrosImp3;
	private BigDecimal total;
	private BigDecimal efectivo;
	private BigDecimal valTerceros;
	private BigDecimal pagares;
	private BigDecimal tarjetas;
	private BigDecimal chequesPropios;
	private BigDecimal monExt;
	private String urgencia;
	private Date fechaEntrega;
	private String ordenCompra;
	private Date fechaEstPago;
	private Integer destino;
	private BigDecimal saldo;
	private Float cuotas;
	private Integer nrDomicilioEnt;
	private int imputacionContable;
	private Short ingreBrutos;
	private Float bultos;
	private Float peso;
	private BigDecimal valor;
	private String proce;
	private String riesgo;
	private String flete;
	private Blob objetoOle;
	private BigDecimal p;
	private BigDecimal r;
	private Integer tranRemitoOrig;
	private Integer tranReciboFact;
	private Integer tranFactCred;
	private BigDecimal factCred;
	private Integer benef;
	private BigDecimal modu;
	private String cae;
	private String fechaCae;

	public Transac() {
	}

	public Transac(int transacNr, int genteNr, Date fecha, int tipoComprob,
			String nrComprob, String letra, String prefijo, int vendedor,
			int cobrador, int condiciones, int tipoIva, float alicuotaIva,
			float sobreAlicIva, float alicuotaInternos, float valorMonExt,
			Date fechaTransac, short vencim1, short vencim2, short vencim3,
			short vencim4, int nrSucursal, int nrOperador, BigDecimal netoGrav,
			BigDecimal netoNoGrav, BigDecimal iva, BigDecimal ivaRni,
			BigDecimal ivaPercep, BigDecimal internos, BigDecimal retIb,
			BigDecimal retIva, BigDecimal retGan, BigDecimal retCargasSoc,
			BigDecimal descuentos, BigDecimal otrosImp1, BigDecimal otrosImp2,
			BigDecimal otrosImp3, BigDecimal total, BigDecimal efectivo,
			BigDecimal valTerceros, BigDecimal pagares, BigDecimal tarjetas,
			BigDecimal chequesPropios, BigDecimal monExt, BigDecimal saldo,
			int imputacionContable, BigDecimal p, BigDecimal r,
			BigDecimal factCred) {
		this.transacNr = transacNr;
		this.genteNr = genteNr;
		this.fecha = fecha;
		this.tipoComprob = tipoComprob;
		this.nrComprob = nrComprob;
		this.letra = letra;
		this.prefijo = prefijo;
		this.vendedor = vendedor;
		this.cobrador = cobrador;
		this.condiciones = condiciones;
		this.tipoIva = tipoIva;
		this.alicuotaIva = alicuotaIva;
		this.sobreAlicIva = sobreAlicIva;
		this.alicuotaInternos = alicuotaInternos;
		this.valorMonExt = valorMonExt;
		this.fechaTransac = fechaTransac;
		this.vencim1 = vencim1;
		this.vencim2 = vencim2;
		this.vencim3 = vencim3;
		this.vencim4 = vencim4;
		this.nrSucursal = nrSucursal;
		this.nrOperador = nrOperador;
		this.netoGrav = netoGrav;
		this.netoNoGrav = netoNoGrav;
		this.iva = iva;
		this.ivaRni = ivaRni;
		this.ivaPercep = ivaPercep;
		this.internos = internos;
		this.retIb = retIb;
		this.retIva = retIva;
		this.retGan = retGan;
		this.retCargasSoc = retCargasSoc;
		this.descuentos = descuentos;
		this.otrosImp1 = otrosImp1;
		this.otrosImp2 = otrosImp2;
		this.otrosImp3 = otrosImp3;
		this.total = total;
		this.efectivo = efectivo;
		this.valTerceros = valTerceros;
		this.pagares = pagares;
		this.tarjetas = tarjetas;
		this.chequesPropios = chequesPropios;
		this.monExt = monExt;
		this.saldo = saldo;
		this.imputacionContable = imputacionContable;
		this.p = p;
		this.r = r;
		this.factCred = factCred;
	}

	public Transac(int transacNr, int genteNr, Date fecha, int tipoComprob,
			String nrComprob, String letra, String prefijo, int vendedor,
			int cobrador, int condiciones, int tipoIva, float alicuotaIva,
			float sobreAlicIva, float alicuotaInternos, float valorMonExt,
			Date fechaTransac, short vencim1, short vencim2, short vencim3,
			short vencim4, int nrSucursal, int nrOperador,
			String observaciones, BigDecimal netoGrav, BigDecimal netoNoGrav,
			BigDecimal iva, BigDecimal ivaRni, BigDecimal ivaPercep,
			BigDecimal internos, BigDecimal retIb, BigDecimal retIva,
			BigDecimal retGan, BigDecimal retCargasSoc, BigDecimal descuentos,
			BigDecimal otrosImp1, BigDecimal otrosImp2, BigDecimal otrosImp3,
			BigDecimal total, BigDecimal efectivo, BigDecimal valTerceros,
			BigDecimal pagares, BigDecimal tarjetas, BigDecimal chequesPropios,
			BigDecimal monExt, String urgencia, Date fechaEntrega,
			String ordenCompra, Date fechaEstPago, Integer destino,
			BigDecimal saldo, Float cuotas, Integer nrDomicilioEnt,
			int imputacionContable, Short ingreBrutos, Float bultos,
			Float peso, BigDecimal valor, String proce, String riesgo,
			String flete, Blob objetoOle, BigDecimal p, BigDecimal r,
			Integer tranRemitoOrig, Integer tranReciboFact,
			Integer tranFactCred, BigDecimal factCred, Integer benef,
			BigDecimal modu, String cae, String fechaCae) {
		this.transacNr = transacNr;
		this.genteNr = genteNr;
		this.fecha = fecha;
		this.tipoComprob = tipoComprob;
		this.nrComprob = nrComprob;
		this.letra = letra;
		this.prefijo = prefijo;
		this.vendedor = vendedor;
		this.cobrador = cobrador;
		this.condiciones = condiciones;
		this.tipoIva = tipoIva;
		this.alicuotaIva = alicuotaIva;
		this.sobreAlicIva = sobreAlicIva;
		this.alicuotaInternos = alicuotaInternos;
		this.valorMonExt = valorMonExt;
		this.fechaTransac = fechaTransac;
		this.vencim1 = vencim1;
		this.vencim2 = vencim2;
		this.vencim3 = vencim3;
		this.vencim4 = vencim4;
		this.nrSucursal = nrSucursal;
		this.nrOperador = nrOperador;
		this.observaciones = observaciones;
		this.netoGrav = netoGrav;
		this.netoNoGrav = netoNoGrav;
		this.iva = iva;
		this.ivaRni = ivaRni;
		this.ivaPercep = ivaPercep;
		this.internos = internos;
		this.retIb = retIb;
		this.retIva = retIva;
		this.retGan = retGan;
		this.retCargasSoc = retCargasSoc;
		this.descuentos = descuentos;
		this.otrosImp1 = otrosImp1;
		this.otrosImp2 = otrosImp2;
		this.otrosImp3 = otrosImp3;
		this.total = total;
		this.efectivo = efectivo;
		this.valTerceros = valTerceros;
		this.pagares = pagares;
		this.tarjetas = tarjetas;
		this.chequesPropios = chequesPropios;
		this.monExt = monExt;
		this.urgencia = urgencia;
		this.fechaEntrega = fechaEntrega;
		this.ordenCompra = ordenCompra;
		this.fechaEstPago = fechaEstPago;
		this.destino = destino;
		this.saldo = saldo;
		this.cuotas = cuotas;
		this.nrDomicilioEnt = nrDomicilioEnt;
		this.imputacionContable = imputacionContable;
		this.ingreBrutos = ingreBrutos;
		this.bultos = bultos;
		this.peso = peso;
		this.valor = valor;
		this.proce = proce;
		this.riesgo = riesgo;
		this.flete = flete;
		this.objetoOle = objetoOle;
		this.p = p;
		this.r = r;
		this.tranRemitoOrig = tranRemitoOrig;
		this.tranReciboFact = tranReciboFact;
		this.tranFactCred = tranFactCred;
		this.factCred = factCred;
		this.benef = benef;
		this.modu = modu;
		this.cae = cae;
		this.fechaCae = fechaCae;
	}

	public int getTransacNr() {
		return this.transacNr;
	}

	public void setTransacNr(int transacNr) {
		this.transacNr = transacNr;
	}

	public int getGenteNr() {
		return this.genteNr;
	}

	public void setGenteNr(int genteNr) {
		this.genteNr = genteNr;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public int getTipoComprob() {
		return this.tipoComprob;
	}

	public void setTipoComprob(int tipoComprob) {
		this.tipoComprob = tipoComprob;
	}

	public String getNrComprob() {
		return this.nrComprob;
	}

	public void setNrComprob(String nrComprob) {
		this.nrComprob = nrComprob;
	}

	public String getLetra() {
		return this.letra;
	}

	public void setLetra(String letra) {
		this.letra = letra;
	}

	public String getPrefijo() {
		return this.prefijo;
	}

	public void setPrefijo(String prefijo) {
		this.prefijo = prefijo;
	}

	public int getVendedor() {
		return this.vendedor;
	}

	public void setVendedor(int vendedor) {
		this.vendedor = vendedor;
	}

	public int getCobrador() {
		return this.cobrador;
	}

	public void setCobrador(int cobrador) {
		this.cobrador = cobrador;
	}

	public int getCondiciones() {
		return this.condiciones;
	}

	public void setCondiciones(int condiciones) {
		this.condiciones = condiciones;
	}

	public int getTipoIva() {
		return this.tipoIva;
	}

	public void setTipoIva(int tipoIva) {
		this.tipoIva = tipoIva;
	}

	public float getAlicuotaIva() {
		return this.alicuotaIva;
	}

	public void setAlicuotaIva(float alicuotaIva) {
		this.alicuotaIva = alicuotaIva;
	}

	public float getSobreAlicIva() {
		return this.sobreAlicIva;
	}

	public void setSobreAlicIva(float sobreAlicIva) {
		this.sobreAlicIva = sobreAlicIva;
	}

	public float getAlicuotaInternos() {
		return this.alicuotaInternos;
	}

	public void setAlicuotaInternos(float alicuotaInternos) {
		this.alicuotaInternos = alicuotaInternos;
	}

	public float getValorMonExt() {
		return this.valorMonExt;
	}

	public void setValorMonExt(float valorMonExt) {
		this.valorMonExt = valorMonExt;
	}

	public Date getFechaTransac() {
		return this.fechaTransac;
	}

	public void setFechaTransac(Date fechaTransac) {
		this.fechaTransac = fechaTransac;
	}

	public short getVencim1() {
		return this.vencim1;
	}

	public void setVencim1(short vencim1) {
		this.vencim1 = vencim1;
	}

	public short getVencim2() {
		return this.vencim2;
	}

	public void setVencim2(short vencim2) {
		this.vencim2 = vencim2;
	}

	public short getVencim3() {
		return this.vencim3;
	}

	public void setVencim3(short vencim3) {
		this.vencim3 = vencim3;
	}

	public short getVencim4() {
		return this.vencim4;
	}

	public void setVencim4(short vencim4) {
		this.vencim4 = vencim4;
	}

	public int getNrSucursal() {
		return this.nrSucursal;
	}

	public void setNrSucursal(int nrSucursal) {
		this.nrSucursal = nrSucursal;
	}

	public int getNrOperador() {
		return this.nrOperador;
	}

	public void setNrOperador(int nrOperador) {
		this.nrOperador = nrOperador;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public BigDecimal getNetoGrav() {
		return this.netoGrav;
	}

	public void setNetoGrav(BigDecimal netoGrav) {
		this.netoGrav = netoGrav;
	}

	public BigDecimal getNetoNoGrav() {
		return this.netoNoGrav;
	}

	public void setNetoNoGrav(BigDecimal netoNoGrav) {
		this.netoNoGrav = netoNoGrav;
	}

	public BigDecimal getIva() {
		return this.iva;
	}

	public void setIva(BigDecimal iva) {
		this.iva = iva;
	}

	public BigDecimal getIvaRni() {
		return this.ivaRni;
	}

	public void setIvaRni(BigDecimal ivaRni) {
		this.ivaRni = ivaRni;
	}

	public BigDecimal getIvaPercep() {
		return this.ivaPercep;
	}

	public void setIvaPercep(BigDecimal ivaPercep) {
		this.ivaPercep = ivaPercep;
	}

	public BigDecimal getInternos() {
		return this.internos;
	}

	public void setInternos(BigDecimal internos) {
		this.internos = internos;
	}

	public BigDecimal getRetIb() {
		return this.retIb;
	}

	public void setRetIb(BigDecimal retIb) {
		this.retIb = retIb;
	}

	public BigDecimal getRetIva() {
		return this.retIva;
	}

	public void setRetIva(BigDecimal retIva) {
		this.retIva = retIva;
	}

	public BigDecimal getRetGan() {
		return this.retGan;
	}

	public void setRetGan(BigDecimal retGan) {
		this.retGan = retGan;
	}

	public BigDecimal getRetCargasSoc() {
		return this.retCargasSoc;
	}

	public void setRetCargasSoc(BigDecimal retCargasSoc) {
		this.retCargasSoc = retCargasSoc;
	}

	public BigDecimal getDescuentos() {
		return this.descuentos;
	}

	public void setDescuentos(BigDecimal descuentos) {
		this.descuentos = descuentos;
	}

	public BigDecimal getOtrosImp1() {
		return this.otrosImp1;
	}

	public void setOtrosImp1(BigDecimal otrosImp1) {
		this.otrosImp1 = otrosImp1;
	}

	public BigDecimal getOtrosImp2() {
		return this.otrosImp2;
	}

	public void setOtrosImp2(BigDecimal otrosImp2) {
		this.otrosImp2 = otrosImp2;
	}

	public BigDecimal getOtrosImp3() {
		return this.otrosImp3;
	}

	public void setOtrosImp3(BigDecimal otrosImp3) {
		this.otrosImp3 = otrosImp3;
	}

	public BigDecimal getTotal() {
		return this.total;
	}

	public void setTotal(BigDecimal total) {
		this.total = total;
	}

	public BigDecimal getEfectivo() {
		return this.efectivo;
	}

	public void setEfectivo(BigDecimal efectivo) {
		this.efectivo = efectivo;
	}

	public BigDecimal getValTerceros() {
		return this.valTerceros;
	}

	public void setValTerceros(BigDecimal valTerceros) {
		this.valTerceros = valTerceros;
	}

	public BigDecimal getPagares() {
		return this.pagares;
	}

	public void setPagares(BigDecimal pagares) {
		this.pagares = pagares;
	}

	public BigDecimal getTarjetas() {
		return this.tarjetas;
	}

	public void setTarjetas(BigDecimal tarjetas) {
		this.tarjetas = tarjetas;
	}

	public BigDecimal getChequesPropios() {
		return this.chequesPropios;
	}

	public void setChequesPropios(BigDecimal chequesPropios) {
		this.chequesPropios = chequesPropios;
	}

	public BigDecimal getMonExt() {
		return this.monExt;
	}

	public void setMonExt(BigDecimal monExt) {
		this.monExt = monExt;
	}

	public String getUrgencia() {
		return this.urgencia;
	}

	public void setUrgencia(String urgencia) {
		this.urgencia = urgencia;
	}

	public Date getFechaEntrega() {
		return this.fechaEntrega;
	}

	public void setFechaEntrega(Date fechaEntrega) {
		this.fechaEntrega = fechaEntrega;
	}

	public String getOrdenCompra() {
		return this.ordenCompra;
	}

	public void setOrdenCompra(String ordenCompra) {
		this.ordenCompra = ordenCompra;
	}

	public Date getFechaEstPago() {
		return this.fechaEstPago;
	}

	public void setFechaEstPago(Date fechaEstPago) {
		this.fechaEstPago = fechaEstPago;
	}

	public Integer getDestino() {
		return this.destino;
	}

	public void setDestino(Integer destino) {
		this.destino = destino;
	}

	public BigDecimal getSaldo() {
		return this.saldo;
	}

	public void setSaldo(BigDecimal saldo) {
		this.saldo = saldo;
	}

	public Float getCuotas() {
		return this.cuotas;
	}

	public void setCuotas(Float cuotas) {
		this.cuotas = cuotas;
	}

	public Integer getNrDomicilioEnt() {
		return this.nrDomicilioEnt;
	}

	public void setNrDomicilioEnt(Integer nrDomicilioEnt) {
		this.nrDomicilioEnt = nrDomicilioEnt;
	}

	public int getImputacionContable() {
		return this.imputacionContable;
	}

	public void setImputacionContable(int imputacionContable) {
		this.imputacionContable = imputacionContable;
	}

	public Short getIngreBrutos() {
		return this.ingreBrutos;
	}

	public void setIngreBrutos(Short ingreBrutos) {
		this.ingreBrutos = ingreBrutos;
	}

	public Float getBultos() {
		return this.bultos;
	}

	public void setBultos(Float bultos) {
		this.bultos = bultos;
	}

	public Float getPeso() {
		return this.peso;
	}

	public void setPeso(Float peso) {
		this.peso = peso;
	}

	public BigDecimal getValor() {
		return this.valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

	public String getProce() {
		return this.proce;
	}

	public void setProce(String proce) {
		this.proce = proce;
	}

	public String getRiesgo() {
		return this.riesgo;
	}

	public void setRiesgo(String riesgo) {
		this.riesgo = riesgo;
	}

	public String getFlete() {
		return this.flete;
	}

	public void setFlete(String flete) {
		this.flete = flete;
	}

	public Blob getObjetoOle() {
		return this.objetoOle;
	}

	public void setObjetoOle(Blob objetoOle) {
		this.objetoOle = objetoOle;
	}

	public BigDecimal getP() {
		return this.p;
	}

	public void setP(BigDecimal p) {
		this.p = p;
	}

	public BigDecimal getR() {
		return this.r;
	}

	public void setR(BigDecimal r) {
		this.r = r;
	}

	public Integer getTranRemitoOrig() {
		return this.tranRemitoOrig;
	}

	public void setTranRemitoOrig(Integer tranRemitoOrig) {
		this.tranRemitoOrig = tranRemitoOrig;
	}

	public Integer getTranReciboFact() {
		return this.tranReciboFact;
	}

	public void setTranReciboFact(Integer tranReciboFact) {
		this.tranReciboFact = tranReciboFact;
	}

	public Integer getTranFactCred() {
		return this.tranFactCred;
	}

	public void setTranFactCred(Integer tranFactCred) {
		this.tranFactCred = tranFactCred;
	}

	public BigDecimal getFactCred() {
		return this.factCred;
	}

	public void setFactCred(BigDecimal factCred) {
		this.factCred = factCred;
	}

	public Integer getBenef() {
		return this.benef;
	}

	public void setBenef(Integer benef) {
		this.benef = benef;
	}

	public BigDecimal getModu() {
		return this.modu;
	}

	public void setModu(BigDecimal modu) {
		this.modu = modu;
	}

	public String getCae() {
		return this.cae;
	}

	public void setCae(String cae) {
		this.cae = cae;
	}

	public String getFechaCae() {
		return this.fechaCae;
	}

	public void setFechaCae(String fechaCae) {
		this.fechaCae = fechaCae;
	}

}
